import type { AppProps } from 'next/app';
import Head from 'next/head';
import type { ReactElement } from 'react';
import React from 'react';
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';

import { persistor, store } from 'constants/reducers';
import { GlobalStyle } from 'styles/App.styles';

export default function ZiventiApp({
  Component,
  pageProps,
}: AppProps): ReactElement {
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <Head>
          <title>Ziventi</title>
          <meta name={'description'} content={'Generated by create next app'} />
          <link rel={'icon'} href={'/favicon-white.png'} />
        </Head>
        <GlobalStyle />
        <Component {...pageProps} />
      </PersistGate>
    </Provider>
  );
}
